apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
  - ./example-copy


patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              group: system
    target:
      kind: (StatefulSet|Deployment|Job)
  - target:
      kind: ConfigMap
      labelSelector: app=jupyter-web-app
    path: patches/jupyter-config.yaml
    
patchesStrategicMerge:
- patches/s3.yaml
- patches/secrets.yaml
- patches/dex.yaml
