apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: kubeflow
stringData:
  accesskey: YCEE8JSMRBC567LNmJGGcWP5qGd5Y2sh
  secretkey: YCMITkPh-vSz4X0gcDaV_XLvgycwTFDgWzA8qDIv