apiVersion: v1
kind: ServiceAccount
metadata:
  name: containerd-fixer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: containerd-fixer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: containerd-fixer
subjects:
- kind: ServiceAccount
  name: containerd-fixer
roleRef:
  kind: Role
  name: containerd-fixer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: containerd-fixer
  labels:
    app: containerd-fixer
spec:
  selector:
    matchLabels:
      app: containerd-fixer
  template:
    metadata:
      labels:
        app: containerd-fixer
    spec:
      serviceAccountName: containerd-fixer
      containers:
        - name: containerd-fixer
          image: cr.nemax.nebius.cloud/k8s/hpc/containerd-fixer:0.0.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/containerd
              name: containerd
            - mountPath: /run/systemd/system
              name: systemd
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: containerd
          hostPath:
            path: /etc/containerd
        - name: systemd
          hostPath:
            path: /run/systemd/system
        - name: dbus
          hostPath:
            path: /var/run/dbus/system_bus_socket
