apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ulimit-fixer
  labels:
    app: ulimit-fixer
spec:
  selector:
    matchLabels:
      app: ulimit-fixer
  template:
    metadata:
      labels:
        app: ulimit-fixer
    spec:
      containers:
        - name: ulimit-fixer
          image: busybox:1.27.2
          command:
            [
              "sh",
              "-c",
              "ulimit -Hl unlimited && ulimit -Sl unlimited; tail -f /dev/null;",
            ]
          securityContext:
            privileged: true
