apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-jupyter.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmnode1
  name: slurmnode1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slurmnode1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-jupyter.yml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/slurm-cluster-default: "true"
        io.kompose.service: slurmnode1
    spec:
      containers:
        - env:
            - name: SLURM_NODENAME
              value: slurmnode1
          image: bpopov/slurm-node
          name: slurmnode1
          resources: {}
          volumeMounts:
            - mountPath: /home/admin
              name: shared-vol
      hostname: slurmnode1
      restartPolicy: Always
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: shared-vol
status: {}
