apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-jupyter.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmnode3
  name: slurmnode3
spec:
  ports:
    - name: "6817"
      port: 6817
      targetPort: 6817
    - name: "6818"
      port: 6818
      targetPort: 6818
    - name: "6819"
      port: 6819
      targetPort: 6819
  selector:
    io.kompose.service: slurmnode3
status:
  loadBalancer: {}
