apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-jupyter.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmjupyter
  name: slurmjupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slurmjupyter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-jupyter.yml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/slurm-cluster-default: "true"
        io.kompose.service: slurmjupyter
    spec:
      containers:
        - image: bpopov/slurm-jupyter
          name: slurmjupyter
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /home/admin
              name: shared-vol
      hostname: slurmjupyter
      restartPolicy: Always
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: shared-vol
status: {}
