apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-jupyter.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmmaster
  name: slurmmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slurmmaster
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-jupyter.yml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/slurm-cluster-default: "true"
        io.kompose.service: slurmmaster
    spec:
      containers:
        - image: bpopov/slurm-master
          name: slurmmaster
          ports:
            - containerPort: 6817
              hostPort: 6817
              protocol: TCP
            - containerPort: 6818
              hostPort: 6818
              protocol: TCP
            - containerPort: 6819
              hostPort: 6819
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /home/admin
              name: shared-vol
      hostname: slurmmaster
      restartPolicy: Always
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: shared-vol
status: {}
