---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc-static
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama2-model-volume
spec:
  storageClassName: csi-s3
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: csi-s3-pvc-static
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: {{ .Values.triton.s3.volumeHandle }}
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    volumeAttributes:
      capacity: 500Gi
      mounter: geesefs
      options: "--memory-limit=500000 --dir-mode=0777 --file-mode=0666 --uid=1001"